import Head from 'next/head'
import Image from 'next/image'
import Hero from '../components/hero/Hero'
import { motion } from "framer-motion"
import AboutSection from '../components/Home/AboutSection'
import SuccessStory from '../components/success/SuccessStory'
import CourseSection from '../components/Home/CourseSection'
import Achievement from '../components/Home/Achievement'
import TestimonialSection from "../components/Home/TestimonialSection"

export default function Home() {
  return (
    <motion.main initial={{ opacity: 0 }} animate={{ opacity: 1, }} exit={{ opacity: 0 }} transition={{ duration: 2 }} className="overflow-x-hidden  mx-auto" >
      <Head>
        <title> Goge Africa</title>
        <meta name="description" content="Generated by create next app" />

      </Head>


      <Hero />
      <AboutSection />
      <SuccessStory />
      <CourseSection />
      <Achievement />
      <TestimonialSection />

    </motion.main>
  )
}
